### ISSUE TITLE
Fail to compile 

### ISSUE THREAD

**Issue by realitix** [realitix/pyshaderc#1]
See https://github.com/google/shaderc/pull/310

**Comment by realitix** [comment]
@dneto0 Let's continue here

**Comment by realitix** [comment]
@dneto0 How did you compile shaderc_combined.a ?
I have added `-DCMAKE_C_FLAGS=-fpic -DCMAKE_CXX_FLAGS=-fpic` during the cmake command. Maybe this is the problem.

Are you on Windows or Linux ? With a 32 or 64 bits machine ?

**Comment by dneto0** [comment]
Works for me now.   I tested it in a virtualenv.
:-)
